version: '3'
services:
  app:
    env_file:
      - .env
    container_name: "node-app"
    environment:
      - POSTGRES_HOST=db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_SERVER_PORT}:${BACKEND_SERVER_PORT}
    depends_on:
      - db
    volumes:
      - .:/home/app
  db:
    env_file:
      - .env
    container_name: ${POSTGRES_DB}
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_PORT: "8080"
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db
